# Generated by Django 4.2.9 on 2024-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_category_article_category_article_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标签")),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(to="api.tag", verbose_name="标签"),
        ),
    ]
