# Generated by Django 4.2.9 on 2024-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_tag_article_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, to="api.tag", verbose_name="标签"
            ),
        ),
    ]
